### ISSUE TITLE
[機能up]複数集計を可能とする

### ISSUE THREAD

**Issue by tmurase-master** [tmurase-master/VBAProjects-C#11]
複数セルの集計を可能にする。

**Comment by Kinoshita0501** [comment]
参考ファイルを見つけて、ソースコードに統合していたところ、構文エラー等が発生しており、完成できておりません。19日中にできなかったら北島さんに協力をお願いします。。。

**Comment by Kinoshita0501** [comment]
【問題】複数セルを配列に入れる際に、空データ（empty、Variant型）も取り込んでいるため、double型に変換して集計する際にエラーが吐いて止まる現象に陥っております。
配列の中のemptyを消去するコードを描く必要があります。
これを行うと、集計対象ファイルとフォーマットの相違が出てしまうと予想されます。。。

**Comment by Kinoshita0501** [comment]
参考ページを見つけ、マージしようとしましたが、ソースの趣旨が違いすぎて出来ませんでした。https://akira55.com/kushizashi/
串さし計算　VBA
すみませんでした。

**Comment by Kinoshita0501** [comment]
北島さん作成のソースコードとマージして完成できました。ありがとうございました。

**Comment by tmurase-master** [comment]
確認しました。完了です。
