### ISSUE TITLE
[修正]集計結果を出力

### ISSUE THREAD

**Issue by tmurase-master** [tmurase-master/VBAProjects-C#8]
集計結果を出力する際に、当該のファイルを開いていると、落ちるため。
修正する。

（修正案）
・集計結果を出力する際に同じファイルある場合は、「同じファイルがあるよ」と注意メッセージを出力して、保存せず閉じる。

**Comment by ssssseiji** [comment]
保存するファイルを開いた状態でマクロを実行したところ、エラー処理が実行され、マクロが落ちませんでした。そのため、保存失敗時に残る集計ファイル（Book1.xls）をクローズさせ、他のエラーと同様に「保存されませんでした」のメッセージを出力させて終了させるようにしようと思います。

**Comment by tmurase-master** [comment]
最新コードのアップ待ち
