### ISSUE TITLE
[修正]集計対象ファイルのオープン

### ISSUE THREAD

**Issue by tmurase-master** [tmurase-master/VBAProjects-C#9]
集計対象ファイルをオープンする際に、すでに対象ファイルを開いていると、落ちる。

修正案
・集計対象ファイルを開くまえに、すでに開かれているかを確認する。
開かれている場合は、注意メッセージを出力して、プログラム終了

**Comment by Madao0492** [comment]
集計対象ファイルと同じファイル名のブックがすでに開かれている場合に、
注意メッセージ＆プログラム終了処理を追加

**Comment by tmurase-master** [comment]
品質保証テストまち
